### ISSUE TITLE
Keymaps question, history undefined behavior?

### ISSUE THREAD

**Issue by Spirarel** [mattmc3/zephyr#11]
Hey there! I'm enjoying antidote. This repo has made adoption much less painful coming from OMZ.

I have two questions I wonder if you could answer,

1. I noticed that like omz, ctrl+p brings up the last command executed, ctrl+o doesn't seem to do anything though, where in omz it runs the command. I think this behavior is from emacs, but I'm not sure. Would I just tack this onto my zshrc as a keybinding or is there a better place to put that?

2. Because you look for XDG_DATA_HOME in the history plugin, on mac this creates a history file for each directory you navigate to in the shell, since this is not exported by default. I can't imagine that's intentional. Is there any benefit to the history plugin when mac generates .zsh_sessions?

**Comment by mattmc3** [comment]
Hey @Spirarel - thank you so much for the bug report. The history thing was definitely a bug. I pushed a new commit that should resolve that. As for the `^O` mapping, I'm only seeing where OMZ maps that in the [`copybuffer` plugin](https://github.com/ohmyzsh/ohmyzsh/blob/5d3e86e2a48adf7a308773f8f1b725d187c7c5ef/plugins/copybuffer/copybuffer.plugin.zsh#L14). I don't see where it runs the command. If you want the copybuffer behavior, it's in Zephyr's new clipboard plugin. Or, if you're using antidote and want the same thing from OMZ, add the following to your `${ZDOTDIR:-$HOME}/.zsh_plugins.txt`:

```txt
ohmyzsh/ohmyzsh path:lib/clipboard.zsh
ohmyzsh/ohmyzsh path:plugins/copybuffer
```

Let me know if this resolves these issues for you, or if you can point me to where OMZ is running the command with a keystroke, I'd be happy to try to add it to Zephyr.

**Comment by Spirarel** [comment]
Hey thanks for pushing that change; I'll be sure to give it a try.

Mmm I don't think it's `copybuffer`, I never had that enabled (unless it's a default?). No, I actually suspect it's [this line in completion.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/5d3e86e2a48adf7a308773f8f1b725d187c7c5ef/lib/completion.zsh#L13). This [SO answer](https://unix.stackexchange.com/a/147575/569577) claims it's default behavior, but that might be true on mac, dunno.

**Comment by mattmc3** [comment]
TIL. Thank you @Spirarel. I pushed a commit with this mapping. Closing this, but feel free to open back up if it's not what you wanted.

**Comment by Spirarel** [comment]
Yeah sure thing! So, I reinstalled `history` and it's working great; just as expected.
The `^o` commit doesn't work though. Probably because whatever `^p` is mapped to isn't traversing the history the [same way as OMZ](https://github.com/ohmyzsh/ohmyzsh/blob/5d3e86e2a48adf7a308773f8f1b725d187c7c5ef/plugins/history-substring-search/README.md?plain=1#L78-L79), sorry I couldn't find where you're mapping it otherwise I would have just make a PR.

Anyway, I don't know what your goal is with the Zephyr; mine certainly isn't to come into your backyard and start making it my own though. So if you're not looking to have this kind of default editor feature parity with OMZ, just let me know and I'll fork 👍 . For instance I also find [these mappings](https://github.com/ohmyzsh/ohmyzsh/blob/5d3e86e2a48adf7a308773f8f1b725d187c7c5ef/plugins/history-substring-search/README.md?plain=1#L68-L69) very useful. Is this something you want?

**Comment by mattmc3** [comment]
> I don't know what your goal is with the Zephyr; mine certainly isn't to come into your backyard and start making it my own though

I haven't really done a good job of explaining the goals of Zephyr, so I hope you don't mind if I get a few thoughts out that I can reference later - (you're probably sorry you asked now) -

My goal with Zephyr was pretty simple - I wanted to build a fast, full-featured, DIY Zsh config using plugins. But, there weren't good ones (or ones I trusted) for a lot of the core features I had come to rely one in Prezto. Also, Prezto and OMZ weren't really designed to have their core functionality used independently as composable plugins. They have a lot of dependencies and don't always work properly when used piecemeal. I decided to build something where other people coming from OMZ or Prezto didn't have to deal with the same issues I did converting to a DIY config.

Zephyr looks like a framework, but is really just a bunch of independent, composable, core Zsh plugins housed in one project. Assuming you use a plugin manager like [antidote](https://github.com/mattmc3/antidote) that supports nested plugins, you can use all of Zephyr, or just the parts you need to help ease the transition from the big frameworks.

Back to the point at hand - most of Zephyr is just upstream code pulled from those projects, with the dependencies untangled, and a little mix of my own custom stuff. As long as the custom parts don't get too unwieldy, I'm willing to own and maintain those parts. For everything else, I rely on the upstream projects.

So, my calculus for adding things is -
- If OMZ or Prezto does it, and it fits into one of the existing plugins in Zephyr, it's something I'd consider adding
- If OMZ or Prezto doesn't have it, then see if you can get it accepted upstream and it'll make its way into Zephyr that way

If a plugin deviates too far from OMZ/Prezto, then it should really become it's own stand-alone plugin.

> For instance I also find [these mappings](https://github.com/ohmyzsh/ohmyzsh/blob/5d3e86e2a48adf7a308773f8f1b725d187c7c5ef/plugins/history-substring-search/README.md?plain=1#L68-L69) very useful. Is this something you want?

Since it's in OMZ, and since a lot of people (myself included) use history-substring-search, I'd definitely consider adding it.

**Comment by Spirarel** [comment]
Okay perfect, yeah that was close to my impression when finding your reddit post/this repo. Your calculus for adding things is quite clarifying though thanks for taking the time to explain that.

Just to settle some remaining ambiguity: when you say "If OMZ or Prezto does it" I assume you mean fresh-install no-plugins enabled. Is that correct?

**Comment by Spirarel** [comment]
> Yeah sure thing! So, I reinstalled `history` and it's working great; just as expected. The `^o` commit doesn't work though. Probably because whatever `^p` is mapped to isn't traversing the history the [same way as OMZ](https://github.com/ohmyzsh/ohmyzsh/blob/5d3e86e2a48adf7a308773f8f1b725d187c7c5ef/plugins/history-substring-search/README.md?plain=1#L78-L79), sorry I couldn't find where you're mapping it otherwise I would have just make a PR.

I was mistaken. I have a cherrypicked plugins.txt which used `ohmyzsh/ohmyzsh path:plugins/copybuffer` which overwrites the bindkey you added.

**Comment by mattmc3** [comment]
> when you say "If OMZ or Prezto does it" I assume you mean fresh-install no-plugins enabled. Is that correct?

Yes - that's what I mean by core functionality, so to be specific, these are the modules and their upstream mapping:
- clipboard - OMZ (the only place where OMZ plugins are used)
- editor keybinds - Prezto (open to adding more from OMZ's lib)
- terminal - Prezto only
- history - Prezto only
- completion - Prezto only
- environment - Prezto only
- directory - Prezto only
- macos - hybrid Prezto & OMZ
- prompt - Zsh-Utils
- utility - Zsh-Utils/Custom
- color - Zsh-Utils/Custom
- homebrew - Custom
- confd - Custom
- zfunctions - Custom

**Comment by Spirarel** [comment]
Good to know. Probably not a bad idea to consolidate this in a CONTRIBUTORS.md at some point.
