### ISSUE TITLE
How to setup p10k as a prompt and have the instaprompt?

### ISSUE THREAD

**Issue by AlgusDark** [mattmc3/zephyr#13]
Hi, first of all, thank you so much for an amazing project. I'm learning a lot of stuff with your repositories :)

I'm wondering what is the best way to use Zephyr to setup the p10k prompt with instaprompt as I don't use starship.

I was trying to follow the way on how you do it in your ZDOTDIR repo but I'm a little confused.

Some things I would like to do is:
- Have different themes for my prompt like "lean" and "pure"
- Use instaprompt (I don't get this part)
- Be able to change it with the "prompt p10k pure/lean"

Thank you!

**Comment by mattmc3** [comment]
> Hi, first of all, thank you so much for an amazing project. I'm learning a lot of stuff with your repositories

Awesome! Glad some of my stuff can be of help.

> I'm wondering what is the best way to use Zephyr to setup the p10k prompt with instaprompt as I don't use starship.

I made Zephyr to be paired with the antigen family of plugin managers that work with subplugins (eg: [antidote](https://github.com/mattmc3/antidote), antigen, or antibody). I admit, I'm not much of a p10k user, but it's very popular so I've definitely experimented with it a bit and considered including it. However, I've not found it a good fit to include with Zephyr for a number of reasons -

- Unlike OMZ, Prezto, or zsh4humans, Zephyr is meant to be a collection of loosely coupled core Zsh plugins that you can mix-and-match a la carte. You can use whichever parts you want without any dependencies at all - not even on other Zephyr plugins. Zephyr provides the stuff you can't get or find easily as standalone Zsh plugins without picking apart OMZ/Prezto internals.
- PowerLevel10k is already distributed as a plugin. Since it's already a true standalone plugin, there's less of a compelling reason to include it here.
-  PowerLevel10k's configs are very specific to your machine/terminal/font/prompt choices, making it a bad candidate to include with Zephyr as "themes". Starship, on the other hand, works really well as a way to distribute prompt themes as .toml files. It even uses a [discussion board](https://github.com/starship/starship/discussions) to allow users to share themes.
 
 > Some things I would like to do is...

I suspect what you're seeing is some of what I've been experimenting with this in my personal [zsh dotfiles](https://github.com/mattmc3/zdotdir). I can give you a quick-and-dirty version of what you're trying to do, but it's pretty hacky and @romkatv could probably help more. Assuming you are not using a plugin manager like [antidote](https://github.com/mattmc3/antidote), here's a config that might work for what you're doing:

First, get powerlevel10k from an **interactive** Zsh session:

```zsh
ZHOME=${ZDOTDIR:-$HOME/.config/zsh} && mkdir -p $ZHOME
git clone --depth 1 https://github.com/romkatv/powerlevel10k $ZHOME/plugins/powerlevel10k
source $ZHOME/plugins/powerlevel10k/powerlevel10k.zsh-theme
```

Follow the `p10k configure` prompts and make your `pure` or `lean` config. When it asks you to "Apply changes to ~/.config/zsh/.zshrc", **DO NOT** have it write to your `.zshrc` unless you really, really need it to to see what it does. We will add those lines ourselves later. `p10k configure` will save your selections to a `$ZDOTDIR/.p10k.zsh` file. 

Next, copy that file to your themes directory:

```zsh
$ cp ${ZDOTDIR:-$HOME/.p10k.zsh} $ZHOME/themes/lean.p10k.zsh
```

Run `p10k configure` as many times as you want to make your starter themes. Now, onto the actual Zsh config.

Next, make a 'myp10k' wrapper function in `$ZDOTDIR/functions/prompt_myp10k_setup`:

```zsh
# $ZDOTDIR/functions/prompt_myp10k_setup
#function prompt_myp10k_setup {
local -a configs=(
  $ZDOTDIR/themes/$1.p10k.zsh(N)
  $ZDOTDIR/.p10k.zsh(N)
)
(( $#configs )) && source $configs[1]
prompt_powerlevel10k_setup
#}

Then, do something like this in your .zshrc:

```zsh
# add prompts to your fpath
fpath=(
)

# initialize the zsh prompt system
autoload -Uz promptinit && promptinit

# clone p10k
ZPLUGINDIR=${ZDOTDIR:-$HOME/.config/zsh/plugins}
[[ -e $ZPLUGINDIR/powerlevel10k ]] ||
  git clone --depth 1 https://github.com/romkatv/powerlevel10k $ZPLUGINDIR/powerlevel10k

# add p10k to your fpath

```



### GENERATED BY p10k configure {{{
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
### END GENERATED }}}

**Comment by mattmc3** [comment]
> Use instaprompt (I don't get this part)

Forgot to mention, you can read more about [instant prompt here](https://github.com/romkatv/powerlevel10k#instant-prompt).

**Comment by AlgusDark** [comment]
Thank you so much for a very helpful comment. I was able to get it done 🙏 
And again, thanks for awesome projects. Antidote is pretty awesome.
